site_name: Policy Machine
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - REST API: api.md
  - Examples: examples.md
  - Contact Us: contact.md
theme:
  name: 'rtd-dropdown'
extra_css:
  - css/extra.css
